import type { IPanacheContext } from './provider/provider'
import { PanacheComponent } from './factory/factory'
import { StyleObject, StyleGenerator } from './types/panache'

declare module panache {
  const ThemeContext: React.Context<IPanacheContext>
  const ThemeProvider: React.Provider<any>
  function address(style: StyleObject | StyleGenerator): PanacheComponent
  function article(style: StyleObject | StyleGenerator): PanacheComponent
  function aside(style: StyleObject | StyleGenerator): PanacheComponent
  function footer(style: StyleObject | StyleGenerator): PanacheComponent
  function header(style: StyleObject | StyleGenerator): PanacheComponent
  function h1(style: StyleObject | StyleGenerator): PanacheComponent
  function h2(style: StyleObject | StyleGenerator): PanacheComponent
  function h3(style: StyleObject | StyleGenerator): PanacheComponent
  function h4(style: StyleObject | StyleGenerator): PanacheComponent
  function h5(style: StyleObject | StyleGenerator): PanacheComponent
  function h6(style: StyleObject | StyleGenerator): PanacheComponent
  function hgroup(style: StyleObject | StyleGenerator): PanacheComponent
  function main(style: StyleObject | StyleGenerator): PanacheComponent
  function nav(style: StyleObject | StyleGenerator): PanacheComponent
  function section(style: StyleObject | StyleGenerator): PanacheComponent
  function blockquote(style: StyleObject | StyleGenerator): PanacheComponent
  function dd(style: StyleObject | StyleGenerator): PanacheComponent
  function div(style: StyleObject | StyleGenerator): PanacheComponent
  function dl(style: StyleObject | StyleGenerator): PanacheComponent
  function dt(style: StyleObject | StyleGenerator): PanacheComponent
  function figcaption(style: StyleObject | StyleGenerator): PanacheComponent
  function figure(style: StyleObject | StyleGenerator): PanacheComponent
  function hr(style: StyleObject | StyleGenerator): PanacheComponent
  function li(style: StyleObject | StyleGenerator): PanacheComponent
  function ol(style: StyleObject | StyleGenerator): PanacheComponent
  function p(style: StyleObject | StyleGenerator): PanacheComponent
  function pre(style: StyleObject | StyleGenerator): PanacheComponent
  function ul(style: StyleObject | StyleGenerator): PanacheComponent
  function a(style: StyleObject | StyleGenerator): PanacheComponent
  function abbr(style: StyleObject | StyleGenerator): PanacheComponent
  function b(style: StyleObject | StyleGenerator): PanacheComponent
  function bdi(style: StyleObject | StyleGenerator): PanacheComponent
  function bdo(style: StyleObject | StyleGenerator): PanacheComponent
  function br(style: StyleObject | StyleGenerator): PanacheComponent
  function cite(style: StyleObject | StyleGenerator): PanacheComponent
  function code(style: StyleObject | StyleGenerator): PanacheComponent
  function data(style: StyleObject | StyleGenerator): PanacheComponent
  function dfn(style: StyleObject | StyleGenerator): PanacheComponent
  function em(style: StyleObject | StyleGenerator): PanacheComponent
  function i(style: StyleObject | StyleGenerator): PanacheComponent
  function kbd(style: StyleObject | StyleGenerator): PanacheComponent
  function mark(style: StyleObject | StyleGenerator): PanacheComponent
  function q(style: StyleObject | StyleGenerator): PanacheComponent
  function rb(style: StyleObject | StyleGenerator): PanacheComponent
  function rp(style: StyleObject | StyleGenerator): PanacheComponent
  function rt(style: StyleObject | StyleGenerator): PanacheComponent
  function rtc(style: StyleObject | StyleGenerator): PanacheComponent
  function ruby(style: StyleObject | StyleGenerator): PanacheComponent
  function s(style: StyleObject | StyleGenerator): PanacheComponent
  function samp(style: StyleObject | StyleGenerator): PanacheComponent
  function small(style: StyleObject | StyleGenerator): PanacheComponent
  function span(style: StyleObject | StyleGenerator): PanacheComponent
  function strong(style: StyleObject | StyleGenerator): PanacheComponent
  function sub(style: StyleObject | StyleGenerator): PanacheComponent
  function sup(style: StyleObject | StyleGenerator): PanacheComponent
  function time(style: StyleObject | StyleGenerator): PanacheComponent
  function u(style: StyleObject | StyleGenerator): PanacheComponent
  // function var(style: StyleObject | StyleGenerator): PanacheComponent
  function wbr(style: StyleObject | StyleGenerator): PanacheComponent
  function area(style: StyleObject | StyleGenerator): PanacheComponent
  function audio(style: StyleObject | StyleGenerator): PanacheComponent
  function img(style: StyleObject | StyleGenerator): PanacheComponent
  function map(style: StyleObject | StyleGenerator): PanacheComponent
  function track(style: StyleObject | StyleGenerator): PanacheComponent
  function video(style: StyleObject | StyleGenerator): PanacheComponent
  function embed(style: StyleObject | StyleGenerator): PanacheComponent
  function iframe(style: StyleObject | StyleGenerator): PanacheComponent
  function object(style: StyleObject | StyleGenerator): PanacheComponent
  function param(style: StyleObject | StyleGenerator): PanacheComponent
  function picture(style: StyleObject | StyleGenerator): PanacheComponent
  function source(style: StyleObject | StyleGenerator): PanacheComponent
  function canvas(style: StyleObject | StyleGenerator): PanacheComponent
  function noscript(style: StyleObject | StyleGenerator): PanacheComponent
  function script(style: StyleObject | StyleGenerator): PanacheComponent
  function del(style: StyleObject | StyleGenerator): PanacheComponent
  function ins(style: StyleObject | StyleGenerator): PanacheComponent
  function caption(style: StyleObject | StyleGenerator): PanacheComponent
  function col(style: StyleObject | StyleGenerator): PanacheComponent
  function colgroup(style: StyleObject | StyleGenerator): PanacheComponent
  function table(style: StyleObject | StyleGenerator): PanacheComponent
  function tbody(style: StyleObject | StyleGenerator): PanacheComponent
  function td(style: StyleObject | StyleGenerator): PanacheComponent
  function tfoot(style: StyleObject | StyleGenerator): PanacheComponent
  function th(style: StyleObject | StyleGenerator): PanacheComponent
  function thead(style: StyleObject | StyleGenerator): PanacheComponent
  function tr(style: StyleObject | StyleGenerator): PanacheComponent
  function button(style: StyleObject | StyleGenerator): PanacheComponent
  function datalist(style: StyleObject | StyleGenerator): PanacheComponent
  function fieldset(style: StyleObject | StyleGenerator): PanacheComponent
  function form(style: StyleObject | StyleGenerator): PanacheComponent
  function input(style: StyleObject | StyleGenerator): PanacheComponent
  function label(style: StyleObject | StyleGenerator): PanacheComponent
  function legend(style: StyleObject | StyleGenerator): PanacheComponent
  function meter(style: StyleObject | StyleGenerator): PanacheComponent
  function optgroup(style: StyleObject | StyleGenerator): PanacheComponent
  function option(style: StyleObject | StyleGenerator): PanacheComponent
  function output(style: StyleObject | StyleGenerator): PanacheComponent
  function progress(style: StyleObject | StyleGenerator): PanacheComponent
  function select(style: StyleObject | StyleGenerator): PanacheComponent
  function textarea(style: StyleObject | StyleGenerator): PanacheComponent
  function details(style: StyleObject | StyleGenerator): PanacheComponent
  function dialog(style: StyleObject | StyleGenerator): PanacheComponent
  function menu(style: StyleObject | StyleGenerator): PanacheComponent
  function summary(style: StyleObject | StyleGenerator): PanacheComponent
}

export = panache
