import { StyleGenerator, StyleObject } from "./types";

declare namespace panache {
  function address(style: StyleObject | StyleGenerator): React.Component
  function article(style: StyleObject | StyleGenerator): React.Component
  function aside(style: StyleObject | StyleGenerator): React.Component
  function footer(style: StyleObject | StyleGenerator): React.Component
  function header(style: StyleObject | StyleGenerator): React.Component
  function h1(style: StyleObject | StyleGenerator): React.Component
  function h2(style: StyleObject | StyleGenerator): React.Component
  function h3(style: StyleObject | StyleGenerator): React.Component
  function h4(style: StyleObject | StyleGenerator): React.Component
  function h5(style: StyleObject | StyleGenerator): React.Component
  function h6(style: StyleObject | StyleGenerator): React.Component
  function hgroup(style: StyleObject | StyleGenerator): React.Component
  function main(style: StyleObject | StyleGenerator): React.Component
  function nav(style: StyleObject | StyleGenerator): React.Component
  function section(style: StyleObject | StyleGenerator): React.Component
  function blockquote(style: StyleObject | StyleGenerator): React.Component
  function dd(style: StyleObject | StyleGenerator): React.Component
  function div(style: StyleObject | StyleGenerator): React.ElementType
  function dl(style: StyleObject | StyleGenerator): React.Component
  function dt(style: StyleObject | StyleGenerator): React.Component
  function figcaption(style: StyleObject | StyleGenerator): React.Component
  function figure(style: StyleObject | StyleGenerator): React.Component
  function hr(style: StyleObject | StyleGenerator): React.Component
  function li(style: StyleObject | StyleGenerator): React.Component
  function ol(style: StyleObject | StyleGenerator): React.Component
  function p(style: StyleObject | StyleGenerator): React.Component
  function pre(style: StyleObject | StyleGenerator): React.Component
  function ul(style: StyleObject | StyleGenerator): React.Component
  function a(style: StyleObject | StyleGenerator): React.Component
  function abbr(style: StyleObject | StyleGenerator): React.Component
  function b(style: StyleObject | StyleGenerator): React.Component
  function bdi(style: StyleObject | StyleGenerator): React.Component
  function bdo(style: StyleObject | StyleGenerator): React.Component
  function br(style: StyleObject | StyleGenerator): React.Component
  function cite(style: StyleObject | StyleGenerator): React.Component
  function code(style: StyleObject | StyleGenerator): React.Component
  function data(style: StyleObject | StyleGenerator): React.Component
  function dfn(style: StyleObject | StyleGenerator): React.Component
  function em(style: StyleObject | StyleGenerator): React.Component
  function i(style: StyleObject | StyleGenerator): React.Component
  function kbd(style: StyleObject | StyleGenerator): React.Component
  function mark(style: StyleObject | StyleGenerator): React.Component
  function q(style: StyleObject | StyleGenerator): React.Component
  function rb(style: StyleObject | StyleGenerator): React.Component
  function rp(style: StyleObject | StyleGenerator): React.Component
  function rt(style: StyleObject | StyleGenerator): React.Component
  function rtc(style: StyleObject | StyleGenerator): React.Component
  function ruby(style: StyleObject | StyleGenerator): React.Component
  function s(style: StyleObject | StyleGenerator): React.Component
  function samp(style: StyleObject | StyleGenerator): React.Component
  function small(style: StyleObject | StyleGenerator): React.Component
  function span(style: StyleObject | StyleGenerator): React.Component
  function strong(style: StyleObject | StyleGenerator): React.Component
  function sub(style: StyleObject | StyleGenerator): React.Component
  function sup(style: StyleObject | StyleGenerator): React.Component
  function time(style: StyleObject | StyleGenerator): React.Component
  function u(style: StyleObject | StyleGenerator): React.Component
  //function var(style: StyleObject | StyleGenerator): React.Component
  function wbr(style: StyleObject | StyleGenerator): React.Component
  function area(style: StyleObject | StyleGenerator): React.Component
  function audio(style: StyleObject | StyleGenerator): React.Component
  function img(style: StyleObject | StyleGenerator): React.Component
  function map(style: StyleObject | StyleGenerator): React.Component
  function track(style: StyleObject | StyleGenerator): React.Component
  function video(style: StyleObject | StyleGenerator): React.Component
  function embed(style: StyleObject | StyleGenerator): React.Component
  function iframe(style: StyleObject | StyleGenerator): React.Component
  function object(style: StyleObject | StyleGenerator): React.Component
  function param(style: StyleObject | StyleGenerator): React.Component
  function picture(style: StyleObject | StyleGenerator): React.Component
  function source(style: StyleObject | StyleGenerator): React.Component
  function canvas(style: StyleObject | StyleGenerator): React.Component
  function noscript(style: StyleObject | StyleGenerator): React.Component
  function script(style: StyleObject | StyleGenerator): React.Component
  function del(style: StyleObject | StyleGenerator): React.Component
  function ins(style: StyleObject | StyleGenerator): React.Component
  function caption(style: StyleObject | StyleGenerator): React.Component
  function col(style: StyleObject | StyleGenerator): React.Component
  function colgroup(style: StyleObject | StyleGenerator): React.Component
  function table(style: StyleObject | StyleGenerator): React.Component
  function tbody(style: StyleObject | StyleGenerator): React.Component
  function td(style: StyleObject | StyleGenerator): React.Component
  function tfoot(style: StyleObject | StyleGenerator): React.Component
  function th(style: StyleObject | StyleGenerator): React.Component
  function thead(style: StyleObject | StyleGenerator): React.Component
  function tr(style: StyleObject | StyleGenerator): React.Component
  function button(style: StyleObject | StyleGenerator): React.Component
  function datalist(style: StyleObject | StyleGenerator): React.Component
  function fieldset(style: StyleObject | StyleGenerator): React.Component
  function form(style: StyleObject | StyleGenerator): React.Component
  function input(style: StyleObject | StyleGenerator): React.Component
  function label(style: StyleObject | StyleGenerator): React.Component
  function legend(style: StyleObject | StyleGenerator): React.Component
  function meter(style: StyleObject | StyleGenerator): React.Component
  function optgroup(style: StyleObject | StyleGenerator): React.Component
  function option(style: StyleObject | StyleGenerator): React.Component
  function output(style: StyleObject | StyleGenerator): React.Component
  function progress(style: StyleObject | StyleGenerator): React.Component
  function select(style: StyleObject | StyleGenerator): React.Component
  function textarea(style: StyleObject | StyleGenerator): React.Component
  function details(style: StyleObject | StyleGenerator): React.Component
  function dialog(style: StyleObject | StyleGenerator): React.Component
  function menu(style: StyleObject | StyleGenerator): React.Component
  function summary(style: StyleObject | StyleGenerator): React.Component
}

export = panache